### ISSUE TITLE
Submit extension also in Open VSX store

### ISSUE THREAD

**Issue by bittner** [ev3dev/vscode-ev3dev-browser#102]
**Is your feature request related to a problem? Please describe.**
Can you submit your extension also in the Open VSX store, please? That would help a lot!

This is a new store for use with VSCodium, to escape the issues related to Microsoft's licensing.

**Describe the solution you'd like**
This extension should be available from https://open-vsx.org/?search=ev3dev

**Additional context**
More infos: https://github.com/VSCodium/vscodium/pull/404

**Comment by dlech** [comment]
It is published now. https://open-vsx.org/extension/ev3dev/ev3dev-browser

It published the current beta version, so it would be awesome if you could test it thoroughly.

**Comment by bittner** [comment]
I managed to flawlessly install the extension in my shiny up-to-date Codium on Ubuntu 18.04.4 LTS. The extension page showed "7 downloads", and now "8 downloads" in Codium, and also the "License" link goes to `open-vsx.org`, which lets me assume it was actually installed from the new store. :+1:
