### ISSUE TITLE
[Question] Difference between stopping the program with EV3 Brick's physical Back/Stop button vs. stopping by VSCode stop button

### ISSUE THREAD

**Issue by AntoniLuongPham** [ev3dev/vscode-ev3dev-browser#103]
I am trying out using multiprocessing in ev3dev2 programs. A very simple program with a parallel process is pasted below: whenever the Touch Sensor is pressed, the Motor shall run.

(A) When I use the physical Back/Stop button on the EV3 Brick to exit the program, the parallel daemon process seems properly terminated.

(B) However, when I exit the program using the VSCode red-square stop button, the daemon process lives on -- when I press the Touch Sensor, the Motor continues to run -- even after VSCode shows: "Program ended by stop button. Completed successfully." I have to reboot the EV3 Brick to kill that process.

Could you let me know the difference between the 2 ways (A) vs. (B) of exiting the program?

```
#!/usr/bin/env python3


from ev3dev2.motor import MediumMotor, OUTPUT_A
from ev3dev2.sensor import INPUT_1
from ev3dev2.sensor.lego import TouchSensor

from multiprocessing import Process


TOUCH_SENSOR = TouchSensor(address=INPUT_1)
MOTOR = MediumMotor(address=OUTPUT_A)


def motor_on_when_touched():
    while True:
        if TOUCH_SENSOR.is_pressed:
            MOTOR.on_for_seconds(
                speed=100,
                seconds=1,
                brake=False,
                block=True)


Process(target=motor_on_when_touched,
        daemon=True).start()
# *** process still alive after program ended through VSCode ***


while True:
    pass
```

**Comment by dlech** [comment]
In theory, they should work the same. But of course reality never exactly matches theory.

When stopping via VS Code it takes a little bit longer because the request has to go through SSH encryption. This delay is usually not noticeable, but when there is a program like this one that is using 100% CPU, it is noticeable.

One thing you can do to improve things is to add a `sleep(0.01)` in both of the `while True:` loops so that the program does not use 100% CPU. Ev3dev is a full Linux operating system, so it needs some CPU cycles free to do other things while your program is running.

The fact that the subprocess is not being killed could be a bug in `brickrun`/`console-runner`.

**Comment by dlech** [comment]
> However, when I exit the program using the VSCode red-square stop button, the daemon process lives on -- when I press the Touch Sensor, the Motor continues to run -- even after VSCode shows: "Program ended by stop button. Completed successfully." I have to reboot the EV3 Brick to kill that process.

The fact that the subprocess is not being killed could be a bug in `brickrun`/`console-runner`.

**Comment by AntoniLuongPham** [comment]
@dlech thank you. Since you have identified #1422 as the underlying problem, shall I close this issue?

**Comment by dlech** [comment]
It is more of an educated guess than a positive identification at this point. :smile: But there probably isn't anything to do in the VS Code extension, so we can close this issue. Does adding `sleep()` fix the problem for you?

**Comment by AntoniLuongPham** [comment]
@dlech adding `sleep(0.01)` does not solve the problem of the subprocess living on. So your https://github.com/ev3dev/ev3dev/issues/1422 is the best diagnosis right now. I'll close this issue here.

P.S. `sleep(0.01)` *does* make the termination delay through VSCode much less, as you said above:
> When stopping via VS Code it takes a little bit longer because the request has to go through SSH encryption. This delay is usually not noticeable, but when there is a program like this one that is using 100% CPU, it is noticeable.

**Comment by dlech** [comment]
I did some more digging and found that this is a VS Code extension bug after all.

**Comment by dlech** [comment]
Can you please try https://github.com/ev3dev/vscode-ev3dev-browser/releases/tag/v1.2.0-beta.2?

The `.vsix` file needs to be downloaded and manually installed - fix is not published in VS Code marketplace yet.

**Comment by AntoniLuongPham** [comment]
@dlech I have installed that 1.2.0 beta and verified that the fix works: all processes are killed by the VSCode stop button. Thank you so much! :)
