### ISSUE TITLE
[Question] How can we `ev3devBrowser.download.exclude` multiple patterns?

### ISSUE THREAD

**Issue by AntoniLuongPham** [ev3dev/vscode-ev3dev-browser#104]
May I check how we can use `ev3devBrowser.download.exclude` to exclude different file patterns? For example, I want to exclude "README*", "pycache" and certain folders such as "test" from downloading onto the EV3 brick.

Thank you very much!

**Comment by dlech** [comment]
see https://github.com/ev3dev/vscode-ev3dev-browser/wiki/Glob-Patterns

**Comment by AntoniLuongPham** [comment]
thank you so much @dlech -- it works :)
