### ISSUE TITLE
Autofill of unwanted command

### ISSUE THREAD

**Issue by eilmi** [ev3dev/vscode-ev3dev-browser#107]
**Describe the bug**
Whether I`m starting a SSH-session to the EV3 by clicking "Open SSH Terminal" or trying to start a program with an interactive window it is always autopasting me c:/Users/username/ev3dev_tests/.venv/Scripts/activate.bat into the terminal which leads to "No such file or directory" in SSH or a "SyntaxError: invalid syntax" when using an interactive window.

**Expected behavior**
No autofilling of this command into the terminal

**Desktop (please complete the following information):**
 - Windows 10
 - Visual Studio Code 1.55.0

![grafik](https://user-images.githubusercontent.com/42511827/113481203-768faf80-9498-11eb-9341-5151ef7a9322.png)

![grafik](https://user-images.githubusercontent.com/42511827/113481215-84453500-9498-11eb-833d-77bc9be469a5.png)

**Comment by dlech** [comment]
This comes from the Microsoft Python extension. You can disable it by setting `"python.terminal.activateEnvironment": false` in you workspace settings. See https://code.visualstudio.com/docs/python/settings-reference.

**Comment by eilmi** [comment]
Thank you so much!
