### ISSUE TITLE
Ability to connect to a different port than 22

### ISSUE THREAD

**Issue by QuercusDS** [ev3dev/vscode-ev3dev-browser#108]
**Problem**
In a distance education environment it would be desirable to have the ability to connect to a different than a default port.
So it would be possible to remotely connect to more than one robot at a specific IP by mapping different ports in NAT to different robots - so each student connects to his own robot.
It requires no change to the existing EV3

**Solution idea**
Add a new setting "port" in ev3devBrowser.additionalDevices.
Using this "port" for establishing the connection instead of the default port 22 in complement to the already existing "ipAddress" would enable to have multiple robots at the same IP

**Comment by dlech** [comment]
Starting with v1.2.1, it is possible to specify a custom port by appending `:<port>` to the IP address.
