### ISSUE TITLE
Handle mulit-root workspaces

### ISSUE THREAD

**Issue by dlech** [ev3dev/vscode-ev3dev-browser#11]
VS Code is moving towards multi-root workspaces

> ### New API for multi-root workspaces
>
> New APIs have been added for multi-root workspaces. The "single root workspace" `workspace.rootPath` variable is now deprecated. Extension authors should use `workspace.workspaceFolders` which is a `WorkspaceFolder` array representing the current list of folders opened in the editor. There is a new event that fires when a folder is added or removed and a function `getWorkspaceFolder` to find a workspace folder for a given resource.

We are using `workspace.rootPath`, so this needs to be changed.

**Comment by WasabiFan** [comment]
Two questions:
- What behavior do we want to adopt? Choose the first workspace?
- What do we want to do when a command involves saving a file locally and there isn't a workspace open?

**Comment by dlech** [comment]
I won't have an opinion until I have played around with mutliroot workspaces and understand how they work. This is low priority for me. And AFAIK this feature is only available in the insiders build currently.

**Comment by WasabiFan** [comment]
Haha, OK... I fully expected you to pounce on any PR that referenced the deprecated option :laughing: I'll go ahead using the existing variable until we figure it out.

**Comment by dlech** [comment]
Getting closer: https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs
