### ISSUE TITLE
Failed to connect to ev3dev: cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by expressy129** [ev3dev/vscode-ev3dev-browser#111]
**Describe the bug**
I just tried to connect to an EV3 brick via VSCode. I followed the instructions outlined [here](https://pybricks.com/ev3-micropython/startrun.html), but every time I try to download and run the program, it says "failed to connect to ev3dev: cannot read property 'startsWith' of undefined". (This seems to indicate that internally ev3dev is using JavaScript)

**To Reproduce**
1. Open an existing project, or create new one
2. Connect to ev3 by plugging in the USB cable
3. Click "connect to device" under the ev3 part of the sidebar
4. Try downloading and running a program,
5. See error in bottom-right

**Expected behavior**
The expectation was for the code to be run and for my robot (spirograph in this case) to start drawing.

**Screenshots**
![image](https://user-images.githubusercontent.com/72491910/133741300-1298b435-8966-4af4-a24f-8ac544d814e9.png)

**Desktop (please complete the following information):**
 - Windows 10 21H1
 
**Additional context**
None.

**Comment by dlech** [comment]
Did you mean to close this issue? Is it working now? If it is not, what is the VS Code version? Can you share the project folder that you are using?

**Comment by expressy129** [comment]
Hi dlech,

I closed this because it worked shortly after I wrote it. I have had no problems since.
