### ISSUE TITLE
Ev3 Python "No module named 'pybricks'"

### ISSUE THREAD

**Issue by ChefVyn** [ev3dev/vscode-ev3dev-browser#114]
**Describe the bug**
Hello i am starting with Ev3 recently but i have been running into a problem 

```
Traceback (most recent call last):
  File "/home/robot/getting_started/main.py", line 2, in <module>
    from pybricks.hubs import EV3Brick
ImportError: No module named 'pybricks'
----------
Exited with error code 1.
```

Does anyone know what the problem is?

I have imported pybricks already and i am using python 3.9.1
![Ev3python](https://user-images.githubusercontent.com/99483590/153592255-52bd5d81-5d2b-493c-bfb5-d22500e7ba31.JPG)

**Comment by dlech** [comment]
Do you have an old version of ev3dev installed on your EV3? You can check like this:

![image](https://user-images.githubusercontent.com/963645/153636119-5d4dd27a-5e13-450c-a529-4f502b09e3e2.png)

**Comment by dlech** [comment]
You need to change the shebang to `#usr/bin/env pybricks-micropython`.

**Comment by ChefVyn** [comment]
Ty that fixed it but now its giving me thi
![error2](https://user-images.githubusercontent.com/99483590/153640604-dd742da4-a2ed-45d2-88b1-963a9bbc90d2.JPG)
s

**Comment by dlech** [comment]
The file needs the executable permission set. This should happen automatically. If it doesn't, it usually means there is a blank line, spaces or hidden characters before the shebang. The `#!` has to be absolutely the first thing in the file.

**Comment by ChefVyn** [comment]
There is nothing in fron
![error2](https://user-images.githubusercontent.com/99483590/153647826-64b05030-c95e-4c41-8f6d-75af39b3dbf0.JPG)
t

**Comment by dlech** [comment]
Sorry, I made a typo, it needs to be  `#!/usr/bin/env pybricks-micropython`.

**Comment by ChefVyn** [comment]
TY! that was the problem
