### ISSUE TITLE
Failed to connect to ev3dev: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by patricksterlin** [ev3dev/vscode-ev3dev-browser#115]
Hi,
I get this error while trying to connect my ev3 brick: "Failed to connect to ev3dev: Timed out while waiting for handshake"
I'm on MacOS.
The problem had been signalled in issue #82 and solved by changing the SSH timeout from 10 to 20 seconds. Either that's been reverted by now or it doesn't do the trick anymore.
I'd be very grateful for some help.

**Comment by patricksterlin** [comment]
I go through the 5 steps of figure 2.5 in the instructions:
1. Open File Tab
2. Connect the EV3 with the cable
3. Open Device Browser
4. Search for my EV brick: 
5. Select my EV Brick. it appears as ev3dev: The status says 'Connecting...' and the dot in front of my device turns yellow 
After a little while, I get the error message: 'Failed to connect to ev3dev: Timed out while waiting for handshake'
And the dot in front of ev3dev is red.

<img width="267" alt="Screen Shot 2023-05-17 at 21 11 43" src="https://github.com/ev3dev/vscode-ev3dev-browser/assets/4385519/4dc54452-c9eb-465c-a28b-34d1bb1a8c11">
<img width="513" alt="Screen Shot 2023-05-17 at 21 11 57" src="https://github.com/ev3dev/vscode-ev3dev-browser/assets/4385519/a3631e63-1635-4bb4-9a37-e74ce4c76971">
<img width="1012" alt="Screen Shot 2023-05-17 at 21 12 16" src="https://github.com/ev3dev/vscode-ev3dev-browser/assets/4385519/d9219ff7-c046-4764-930b-e628b757c6cb">

**Comment by dlech** [comment]
I just tried this with a fresh install of ev3dev on my mac (macOS v13.3.1, 2021 M1 Pro) and it is working for me.

I think the most likely problem is a defective or corrupt (or extremely slow) microSD card.

**Comment by patricksterlin** [comment]
I'm on MacOS 11.7.3
I tried with two different ev bricks, three different cables and three different SD cards.
The cards do not seem to be corrupted, as they are running the OS fine.
Here is the fastest SD card I have tried. Do you think it is too slow?

![image](https://github.com/ev3dev/vscode-ev3dev-browser/assets/4385519/5f1ff18a-ba98-452e-ab84-119269fdace0)

**Comment by dlech** [comment]
Does regular `ssh` work, e.g. running `ssh robot@ev3dev.local.` in the Terminal app?

**Comment by patricksterlin** [comment]
Nothing seems to be happening, the cursor just goes down a line.
Is there anything else I should be typing in the terminal?

**Comment by dlech** [comment]
I just modified my previous comment to add the user name, but it should have connected anyway.

Another way to try is to use the device discovery in the Terminal app.

<img width="397" alt="image" src="https://github.com/ev3dev/vscode-ev3dev-browser/assets/963645/65b9ec95-baa8-4749-a40f-65b342bae0aa">

It should show `ev3dev` in your case (I have some with different names). You will need to type in the user name `robot`.

<img width="409" alt="image" src="https://github.com/ev3dev/vscode-ev3dev-browser/assets/963645/fa555f61-1caf-40f0-a593-99823616334f">

If you were running Windows, I would think that maybe some security software was blocking port 22, but I've never heard of anything like that on Mac.

**Comment by patricksterlin** [comment]
<img width="575" alt="Screen Shot 2023-05-18 at 12 43 56" src="https://github.com/ev3dev/vscode-ev3dev-browser/assets/4385519/21939680-0bc8-4d95-a142-ca69fbc1d9fe">

Should anything else be happening?

I am running Windscribe VPN. Any chance that can interfere?

**Comment by dlech** [comment]
It should eventually connect or fail. If not, short of logging TCP/IP traffic, I'm not sure what else to suggest. 

> I am running Windscribe VPN. Any chance that can interfere?

The website says it has a firewall, so yes, I suppose it could.

**Comment by patricksterlin** [comment]
It works when Windscribe VPN is off :-)
Thank you so much for your help...
