### ISSUE TITLE
VScode not recognizing ev3 on macos Sonoma

### ISSUE THREAD

**Issue by OptimusPrime321** [ev3dev/vscode-ev3dev-browser#117]
What are you trying to do?

I am trying to code my ev3 with Python on VScode

What did you expect to happen?

After clicking on ev3dev device browser, the ev3 brick will show up, I will click on it and I can then program.

What actually happened

After clicking on the ev3dev device browser, the ev3 brick did not show up when it was connected via wire

Description

I have so far followed the instructions on the official Lego website "https://education.lego.com/en-us/product-resources/mindstorms-ev3/teacher-resources/python-for-ev3/". I have flashed the SD card, and inserted it into the ev3. I am also using the wire. I have also downloaded VS code, updated it to the latest version, and downloaded the "LEGO® MINDSTORMS® EV3 MicroPython" extension. The steps after that on the official site, are to create a new program, click on ev3dev device browser, and finally discover the device. I would also just like to use wired, not any internet/bluetooth-based connection. Also, I don’t want any wire-based Internet connection because the official steps just require a simple wire-based connection

**Comment by dlech** [comment]
Which operating system and operating system version are you using?

**Comment by OptimusPrime321** [comment]
I am using macOS Sonoma 14.0 on a MacBook Air M1. It works, on another laptop which is a Macbook Pro M1 . The brick will never show up, when on the other laptop it shows up in an instant.

**Comment by dlech** [comment]
Is the working computer also running Sonoma 14.0?

**Comment by OptimusPrime321** [comment]
No, the working computer is running macOS Ventura 13.5.1. I recently upgraded to macOS Sonoma 14.0 on the MacBook Air and when the MacBook Air was on macOS Ventura 13.5.1, it also didn't work

**Comment by dlech** [comment]
If one computer worked with the same OS version while another does not, then is sounds like the problem is with the computer. Maybe there is some sort of setting or permission in the operating system settings that is different?

**Comment by OptimusPrime321** [comment]
The MacBook Air, has all admin permissions and I even switched users. Still no luck.

**Comment by dlech** [comment]
Maybe there is some kind of security software installed that could be blocking it?

**Comment by OptimusPrime321** [comment]
There is no VPN-sort of software at all installed. I tried it again, but it is just not recognizing it.

**Comment by OptimusPrime321** [comment]
So, is there anything I can do? I just updated VScode, and it still doesn't work.

**Comment by dlech** [comment]
You would need to do a deep dive into the OS logs to try to figure out what is going on.

**Comment by OptimusPrime321** [comment]
Good news !
I created an entire new user again and it worked.
