### ISSUE TITLE
Device still shows connected when network is physically disconnected

### ISSUE THREAD

**Issue by dlech** [ev3dev/vscode-ev3dev-browser#16]
On Windows, we get a `ECONNRESET` error on the SSH socket as soon as the cable is unplugged. On macOS, there are no errors besides an eventual timeout. We need to find a way to detect the network interface disappearing. Also, we are limited by the fact that we can't use native modules.

**Comment by WasabiFan** [comment]
It seems like we have some variety of a larger issue going on, possibly related. On Windows, if I unplug my brick's Wi-Fi dongle while running a command, sometimes the `exec` call never completes and the device stays listed in the tree but nonfunctional. Subsequent actions cause the SSH session to throw errors about being disconnected but the device remains. This seems to repro consistently until I can't repro it anymore, then it comes back an hour later.

**Comment by dlech** [comment]
I agree, I tried pulling the plug on a wired Ethernet dongle on Linux and had the same sort of problem.

I guess we need some sort of network monitor that periodically does something to see if the connection is still alive.
