### ISSUE TITLE
Only connect to one device at a time

### ISSUE THREAD

**Issue by dlech** [ev3dev/vscode-ev3dev-browser#2]
I know most people only have one EV3, but I am lucky to have many such toys. But I have found it annoying to have more than on device listed in the browse list at a time.

We should only connected to one device at a time, so we will need to change how we discover devices and connect.

https://github.com/ev3dev/ev3dev/issues/788#issuecomment-319124406

**Comment by WasabiFan** [comment]
After playing around with this for a while last night, I can certainly say that the auto-discovery of multiple devices is cool but makes it feel like you're losing control sometimes. I'd propose the following flow:

- By default, no UI for ev3dev is present. The extension provides a command which, when activated, initiates a scan for devices (I assume you're using mDNS)
- Once the timeout is reached, display a picker with each of the discovered bricks and their IP addresses listed as well as an additional option to "Direct connect" or similar
    - If this final option is selected, the user is presented an input box where they can type the IP address or hostname of the brick
- A status bar item is added to indicate that the brick is connected. Clicking it gives you the option to disconnect. The ev3dev file tree also appears with the chosen device.

What do you think about that? I like the fact that it would make our extension non-intrusive until you explicitly invoke a connection.

**Comment by dlech** [comment]
Single device connection is implemented. If there is something in the tree view, you know it is connected. If there is nothing in the tree view, you know it is disconnected.

Tree view can be enabled/disabled via setting. It is enabled globally by default for discoverability, but can be disabled globally and enabled in workspace settings if you want it out of your way when working on other projects.

"Direct connect" is not implemented yet, so open a new issue for that if needed (I'm hoping we can get away without it though).
