### ISSUE TITLE
screenshot date is wrong

### ISSUE THREAD

**Issue by dlech** [ev3dev/vscode-ev3dev-browser#21]
I took a screenshot for the README on 2017-08-26, but it says 2017-07-06...

![screenshot](https://raw.githubusercontent.com/ev3dev/vscode-ev3dev-browser/154988b7424970bcc22a2cdbe14a4f44efa3a24f/.README/screenshot.png).

**Comment by dlech** [comment]
The year and time look right, jut the month and day are wrong

**Comment by WasabiFan** [comment]
What the... 😕
