### ISSUE TITLE
Document build steps

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/vscode-ev3dev-browser#30]
We should add build steps to the README. Current list I have is:

```
git clone https://github.com/ev3dev/vscode-ev3dev-browser
cd vscode-ev3dev-browser
npm install
code .
```

And for building the native module:

```
npm install -g browserify nexe upx
./build-native.{bat,sh}
```
It'd be good to test that to confirm that nothing else is required. I recall performing some extra steps after cloning for the first time. Also, I'm just guessing on the native module front.

**Comment by dlech** [comment]
I don't want this in the readme since the readme is displayed in VS Code itself when browsing extensions.

Let's put all this info on the wiki. I've already started a page.

https://github.com/ev3dev/vscode-ev3dev-browser/wiki/Hacking

**Comment by dlech** [comment]
```
npm install
```

Needs to be

```
npm install --no-optional
```

**Comment by dlech** [comment]
> npm install -g browserify nexe upx

AFAIK, `upx` is not a node module.

**Comment by dlech** [comment]
Building native modules is a real pain, especially on Windows. You have to have build tools setup to build node itself. But, this is not something that most developers will need to do. There are ways to run and debug the modules without doing the native build.

**Comment by dlech** [comment]
Anything else to do here?

**Comment by WasabiFan** [comment]
Have the dependencies been fixed so that running `npm install` installs everything required for a native build, particularly on Windows?

**Comment by dlech** [comment]
No. That is #32.

**Comment by WasabiFan** [comment]
I'm going to close this in favor of the documentation related to #32.
