### ISSUE TITLE
Add support for custom destination directories

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/vscode-ev3dev-browser#36]
It would be helpful if I could specify a custom directory to deploy my files to when I hit the "download" button.

**Comment by dlech** [comment]
This feature already exists via the `ev3devBrowser.download.directory` configuration setting.

**Comment by WasabiFan** [comment]
Ooh, I'll have to try that out later today.

**Comment by WasabiFan** [comment]
Closing after #39
