### ISSUE TITLE
Make it possible to cancel a download operation

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/vscode-ev3dev-browser#37]
Right now, if you begin a download operation and then decide you want to cancel it, you must somehow kill the session. There should be an option to cancel the download (workspace command, status bar item, etc.). This would likely be implemented as a short-circuit between individual file copy operations.

**Comment by markcrosbie** [comment]
Would this work?

https://stackoverflow.com/questions/37824733/how-to-manually-terminate-a-task-in-visual-studio-code

**Comment by dlech** [comment]
Currently, downloads are implemented as a command rather than a task, so no, that won't work.
