### ISSUE TITLE
Screenshot command

### ISSUE THREAD

**Issue by dlech** [ev3dev/vscode-ev3dev-browser#4]
It would be nice to be able to take a screenshot and upload it without using the command line.

**Comment by WasabiFan** [comment]
@dlech Is there a particular way you were thinking of implementing this? Just `fbgrab` then download the file?

**Comment by dlech** [comment]
`fbcat` or `fbgrab` (I don't remember which) can pipe the image output to `stdout`, so we can actually use `Device.exec()` the extension and grab the `stdout` without having to ever create a file.

**Comment by WasabiFan** [comment]
Oh, cool; I think it must be `fbcat` because I was looking for such an option on `fbgrab` earlier and couldn't find it. I'll look into this in a bit.

**Comment by WasabiFan** [comment]
Transplanting from Gitter...

> @dlech I was looking into the screenshot functionality last night; long story short, if we use `fbcat`, we get a PBM file (or PPM if you've hacked together a color display) which is obviously not ideal for a user. Would you prefer that I implement a parser+converter to generate a useful file type (would only take ten minutes to implement but would involve having a PNG or JPEG lib as a dependency) or use `fbgrab` and copy the file over via SSH? I think the former is cleaner but the latter involves less code on our end. Not sure which is more reliable.
