### ISSUE TITLE
vscode plugin disconnects from EV3 after download

### ISSUE THREAD

**Issue by markcrosbie** [ev3dev/vscode-ev3dev-browser#44]
The plugin seems to disconnect from an EV3 after downloading a project, or after a short (indeterminate) period of time. I can't seem to maintain a permanent connection to the EV3 from the plugin. I have two ssh sessions open to the EV3 at the same time with no lag in typing on the terminal.

**Comment by dlech** [comment]
Hi Mark :smile: 

This should be fixed in the next release. It has been tricky finding a balance between too long of a timeout when a USB cable is unplugged and too short of a timeout that causes Bluetooth and Wi-Fi connections to disconnect unexpectedly.

How are you connecting to the EV3?

**Comment by markcrosbie** [comment]
Hi David!

Good to hear; and I see a few of my other enhancement ideas are captured here too (interruptible download, delta sync). I'm connecting over wifi, which works well as terminal sessions seem to go just fine.

**Comment by dlech** [comment]
Be sure to give other issues you are interested in a :+1: via the reaction button ![selection_014](https://user-images.githubusercontent.com/963645/31728880-1fdbb636-b3f3-11e7-8e3e-cf438f98a940.png) so we know to make them a priority.

**Comment by dlech** [comment]
6431962adb0785110f6004c7d6d910fe026694e2

**Comment by dlech** [comment]
I've just released v0.6.0 that should fix this. Please upgrade and let me know if it stays connected.

**Comment by markcrosbie** [comment]
Left it for a minute and it stays connected - thanks!
