### ISSUE TITLE
Improve documentation on download.include/exclude file globbing

### ISSUE THREAD

**Issue by markcrosbie** [ev3dev/vscode-ev3dev-browser#45]
A suggestion on improving the documentation on the ev3devBrowser.download.{include,exclude} settings.

I run vscode from a virtualenv to keep projects isolated. But the virtualenv has a bin, lib and include directory which keep getting downloaded to the EV3 every time I download the project. I struggled to make sense of the file globbing in the include/exclude settings. I wanted to exclude bin/ lib/ and include/ and all . files, but include everything else.

Studying the plugin code the line I saw that this is how files are iterated over for download:
            const files = await vscode.workspace.findFiles(includeFiles, excludeFiles);
but I couldn't figure out how to exclude certain directories.

Maybe some sample documentation on the wiki would help.

**Comment by dlech** [comment]
Glob patterns are not something specific to Visual Studio Code or this extension, so we could probably find a good reference site to link to. Feel free to add any extra examples to the wiki too.

There may be a more concise way to accomplish your specific case, but I think this should work...

> I wanted to exclude bin/ lib/ and include/ and all . files,

    "ev3devBrowser.download.exclude": "{bin/**/*,lib/**/*,include/**/*,**/.*}"

> but include everything else.

    "ev3devBrowser.download.include": "**/*"

**Comment by markcrosbie** [comment]
I cheated and created a src/ folder, put my .py files in there and did:
` {
    "ev3devBrowser.download.include": "src/*"
} `
in the user settings :)

**Comment by dlech** [comment]
I started a wiki page: https://github.com/ev3dev/vscode-ev3dev-browser/wiki/Glob-Patterns
