### ISSUE TITLE
Can't have multiple SSH shells open at once

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/vscode-ev3dev-browser#47]
Using the current version from master, if I open an SSH shell, it works as expected. If I click the button _again_, however, an empty terminal pane is displayed and no output is produced.

**Comment by dlech** [comment]
Works for me with on VS Code 1.17.2 on Linux with master branch.

OS? VSCode version? Extension version?

**Comment by WasabiFan** [comment]
I just upgraded VSCode (not major versions, just a hotfix) and the issue went away; I think it was a VSCode bug.
