### ISSUE TITLE
No run command

### ISSUE THREAD

**Issue by Joshua-Jurgensmeier** [ev3dev/vscode-ev3dev-browser#49]
After downloading a source file to the brick, right-clicking on the file in the browser no longer provides a "Run" option for me.  I have ensured that the downloaded file is executable and has the correct shebang.  Also, I tried it on another computer, and it had the same behavior.  The only two options are "Delete" and "Show details".  I know it had the run option last Thursday, so I would guess one of the recent commits broke this for me.  Both computers are Windows 10 with the latest update of VScode (1.17.2) and version 0.6.0 of the extension.  Thanks!

**Comment by dlech** [comment]
Thanks for reporting. Should be fixed in v0.7.0.
