### ISSUE TITLE
How to better handle executable bit

### ISSUE THREAD

**Issue by dlech** [ev3dev/vscode-ev3dev-browser#5]
No obvious ideas here. Some discussion at <https://github.com/ev3dev/ev3dev/issues/788#issuecomment-319124406>.

**Comment by dlech** [comment]
Probably the best we can do is add a setting for this where you can explicitly list files that should be executable. We can just make `**/*` the default.

**Comment by WasabiFan** [comment]
I think it would be nice to simply be able to (right)-click on a file and choose "Make executable". Having a config file that follows your code is ideal for sharing the project, but for smaller scripts the menu option might work well.

**Comment by dlech** [comment]
Interesting suggestion: https://github.com/ev3dev/ev3dev/issues/788#issuecomment-325531643

**Comment by dlech** [comment]
Since 1fa8667eb3431e959633bbd1004a7c2961fdd0e6, unix platforms transfer host file permissions to remote plus, the executable bit is set for any file that starts with a shebang. On Windows, all files will still be executable since Windows doesn't know about POSIX file permissions.

**Comment by dlech** [comment]
Final resolution is to:
1. make all files with shebang executable
2. use host file permissions on Unix-like host systems
3. make ELF files executable on Windows host systems
