### ISSUE TITLE
USB connection dropping out

### ISSUE THREAD

**Issue by dlech** [ev3dev/vscode-ev3dev-browser#58]
from @ndward https://github.com/ev3dev/ev3dev/issues/1022#issuecomment-381444425

> Another thing I've noticed is that although my USB connection to the EV3 has always been very stable I have lost it several times this evening – I just saw it fail a few seconds ago for no apparent reason (when I was doing nothing), for example. The connection via USB doesn't seem to last more than 10 or 20 minutes. I haven't tried wireless connections with the new image.

**Comment by dlech** [comment]
Also reported by @bittner on Gitter:

> The connection is somewhat "unstable", though, with the USB cable (or it "goes to sleep" quickly?), compared to the WLAN connection, which is super-reliable.

**Comment by WasabiFan** [comment]
I've been running into this for the past several months (at least) as well. My dongle is `ID 0846:9030 NetGear, Inc. WNA1100 Wireless-N 150 [Atheros AR9271]` and the vscode connection dies every, perhaps, five to fifteen minutes. I suspect this is a timeout-related issue, as I notice extreme lag come-and-go intermittently with both vscode and PuTTY connections. I'm not sure what causes the lag, but there isn't anything in `dmesg` relating to it. Are there any timeouts that I might be able to adjust here?

```
========== ev3dev-sysinfo ==========
Image file:         ev3dev-stretch-ev3-generic-2018-07-15
Kernel version:     4.14.55-ev3dev-2.2.0-ev3
Brickman:           0.10.0
BogoMIPS:           148.88
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=00165340720B
BOARD_INFO_TYPE=main
```

**Comment by dlech** [comment]
@WasabiFan, this issue is about Ethernet over USB. It sounds like you are using Wi-Fi. If you have connection problems in PuTTY as well, then this isn't a VS Code issue. You can run `modinfo <name>` on the kernel module to see if there are any parameters you can tweak (use `lsmod` to see what `<name>` might be).

**Comment by WasabiFan** [comment]
I have two problems here:

1. The Wi-Fi connection lags frequently
2. The vscode extension disconnects sometimes

My theory is that the former causes the latter, and while I've been under the assumption that fixing the dongle lag is hard (I'll look into that suggestion), the fact that PuTTY handles it fine (lags but doesn't drop) while the vscode extension often dies makes me think that there's a timeout that should be increased on our side. It seemed to me that this was on-topic for the thread, but maybe I'm misinterpreting it.

**Comment by dlech** [comment]
I misunderstood you previous comment to mean that PuTTY had the exact same issues as VS Code, but I see now that is not the case. There are some old issue about the timeout setting if you want to play around with it.

**Comment by dlech** [comment]
I'm going to guess this was fixed by https://github.com/ev3dev/vscode-ev3dev-browser/commit/9e679097277fa5eff8b91768bc88d11c52f12578. Haven't logged any complaints for quite some time.
