### ISSUE TITLE
RUN <executable> fails

### ISSUE THREAD

**Issue by SharatSingh** [ev3dev/vscode-ev3dev-browser#59]
Running commands from the extension fail with error 127 (bash: No Brickrun found).
Tried installing brickrun on ev3dev, but that has cmake 3.5 dependency that's not buildable on ev3.

Any suggestions, fixes, or workarounds?

**Comment by dlech** [comment]
This extension requires ev3dev-stretch. It will not work with ev3dev-jessie.
