### ISSUE TITLE
Request for fixed version of March 16 Stretch EV3 image

### ISSUE THREAD

**Issue by ndward** [ev3dev/vscode-ev3dev-browser#60]
I like very much the VS Code EV3 extension – it will make it very easy for beginner Python programmers (my target audience) to code for the EV3. But the extension is compatible only with Stretch versions of ev3dev, and so far no Stretch version has been published which does not have major problems. Versions up to and including March 16 2018 had a 'brickd hyperactivity' bug and versions since then (in the words of @dlech)

> include a major kernel upgrade from 4.9 to 4.14, so I suspect there will be multiple new issues related to this.

@dlech suggested in https://github.com/ev3dev/ev3dev-lang-python/issues/455  that 

> if you want an older kernel with fixed brickd, I would suggest using an image older than 14 April and just upgrade the brickd package, but not the kernel (sudo apt update && sudo apt install brickd).

 I've done this, and the updated version works very well. But this update requires an internet connection for the EV3, which beginners might find tricky to set up. Windows users, in particular, will never be able to set up reliable Internet Connection Sharing since, as stated on ev32dev.org, 

> Windows Internet Connection Sharing is temperamental. Sometimes it just stops working for no reason.

If it can be made possible for beginners to get started programming for the EV3 in Python in VS Code without ever needing to connect the EV3 to the internet that would be ideal. (Tethering would also be appropriate, but there are still no instructions available for setting up USB tethering for Windows.) Therefore I request that a Stretch image be published that would simply be the March 16 version but with the brickd update already applied. That would make it possible for the first time for a Stretch image to be installed that is very useable without modification.  If such an image is published I would suggest that its name should be 'backdated'  to snapshot-ev3dev-stretch-ev3-generic-2018-03-17.img.xz  since it would be only a slightly modified version of snapshot-ev3dev-stretch-ev3-generic-2018-03-16.img.xz  and since later versions are very different. Of course, the new release would not contain any Jessie versions and if it doesn't contain anything for RPi or Beaglebone then I would have no problem with that.

**Comment by dlech** [comment]
If there are problems with the most recent stretch images, then we should just fix them. I've already fixed a dozen or more other issues since March, so I'm afraid I don't see much point in creating such an image just to buy us some weeks of easier usability.

**Comment by ndward** [comment]
I'm delighted to read that you are expecting the problems with the new releases to be resolved in just a few weeks – I had assumed it would take longer. I look forward to working with the problem-free version and I thank you for the work you are doing on this. I withdraw my request, of course.

**Comment by dlech** [comment]
I'm not aware of any significant issues that don't already have fixes committed, so it is just a matter of packaging them up.
