### ISSUE TITLE
Font for wifi passcode entry is too large

### ISSUE THREAD

**Issue by ndward** [ev3dev/vscode-ev3dev-browser#63]
In the 15/7/2018 Stretch image the problem of a too-large font being used in the Wifi passcode entry page is still present. This makes the E and F look identical, and the I and L look almost identical. See attached image. I don't know whether this is also a problem in Jessie.
![ev3dev-2018-06-06-17-41-03](https://user-images.githubusercontent.com/9800891/43036265-5fba7e42-8cfe-11e8-8444-4c03b9a9074c.png)

**Comment by WasabiFan** [comment]
This should be an issue on the main ev3dev repo rather than the one for the Code extension.

**Comment by dlech** [comment]
moved :arrow_up:
