### ISSUE TITLE
extension not visible in explorer

### ISSUE THREAD

**Issue by bjornsone** [ev3dev/vscode-ev3dev-browser#66]
The extension was previously visible and fully working in the explorer view of Visual Studio Code.
Now it doesn't show up (see image below) and after reinstalling it still no longer shows up.
I'm using the example project of vscode-hello-python-master without any modifications.
Is there any setting or configuration that controls whether this view is visible within explorer?
![ev3dev-browser](https://user-images.githubusercontent.com/8865007/48817400-2797b400-ecfb-11e8-8895-78453e196808.PNG)

**Comment by dlech** [comment]
* What operating system do you use?
* What version of VS Code do you use? 
* Are there any error messages in the developer tools (*Help > Toggle Developer Tools*)?

**Comment by dlech** [comment]
And yes, I think there is a configuration for this. Search for "ev3dev" in the settings.

**Comment by dlech** [comment]
![selection_015](https://user-images.githubusercontent.com/963645/48857000-7dad3b80-ed7d-11e8-88e4-91a8486b4d60.png)

Actually, it looks like you access it from right-clicking where it says `EXPLORER`.

**Comment by bjornsone** [comment]
Thank you very much for explaining the solution of right-clicking on explorer.  I had try searching in settings, but never tried the right click.
