### ISSUE TITLE
Connect to Device Dialogue not Appearing

### ISSUE THREAD

**Issue by DeltaBravo** [ev3dev/vscode-ev3dev-browser#69]
Arch Linux (rolling release, up-to-date)
Bluetooth 0a5c:217f Broadcom Corp. BCM2045B (BDC-2.1)

Code (vscode)
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-12-06T23:12:09.502Z
Electron: 2.0.14
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

ev3dev
brickman v0.10.0
Kernel: 4.14.80-ev3dev-2.3.1-ev3
Model: LEGO MINDSTORMS EV3
Revision: 0000

"Click here to connect a device"
Clicking does nothing...no dialogue appears.

Using "ev3dev/vscode-hello-python" I attempt to run hello.py and I am prompted with "No ev3dev device is connected."
I click "Connect now" button on prompt...the prompt disappears and nothing more happens.

I was unable to get anything to work with a USB cable connection however I can and am connected via  SSH over Bluetooth during all of the above.

**Comment by WasabiFan** [comment]
What's the output of `ev3dev-sysinfo -m`? I can't recall off the top of my head but that kernel version looks like ev3dev-jessie (old) whereas this extension only supports ev3dev-stretch (beta). I am not 100% sure though.

**Comment by dlech** [comment]
Make sure avahi is installed and running on your computer.

**Comment by DeltaBravo** [comment]
@WasabiFan 
```
Image file:         ev3dev-stretch-ev3-generic-2018-11-13
Kernel version:     4.14.80-ev3dev-2.3.1-ev3
Brickman:           0.10.0
BogoMIPS:           227.32
Board:              board0
BOARD_INFO_HW_REV=8
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=001653612FD2
BOARD_INFO_TYPE=main
```

@dlech Thank you! Although Avahi was installed it was not configured. Once setup vscode-ev3dev-browser worked as expected and I am now connected to my EV3 with 'Code' via Bluetooth.
