### ISSUE TITLE
Harden implementation of SSH terminal

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/vscode-ev3dev-browser#7]
Currently, the SSH solution is to invoke the user's default shell and pass it an argument to run an SSH client. This has a few issues:
- It requires that the SSH client is present in the terminal's working directory
- It requires the user-chosen terminal to conform to the extension's assumption of the input format
- It depends on the user-chosen terminal's handling of escape codes

This could easily cause issues. When I originally looked into this problem, I began by directly creating a terminal with the SSH client as the shell -- e.g., `plink` on Windows. This worked well and was as system-independent as possible, however the escape codes that the server produced had some quirks that weren't handled correctly. I looked into writing a wrapper app to handle those, but that hit a dead end; I simply couldn't find a way to invoke a Node.js app as the terminal and didn't have much interest in writing such a wrapper as a CMD script.

We should definitely look for a better way of handling the SSH sessions to increase reliability and remove as much dependence on the user's system as is reasonable.

**Comment by WasabiFan** [comment]
This has been implemented on Linux, but as far as I can tell the SSH implementation is now broken on other platforms -- there isn't any native module checked in for Windows or macOS.

**Comment by dlech** [comment]
Patience, young padawan. :wink:
