### ISSUE TITLE
VS Code tab problems

### ISSUE THREAD

**Issue by marchanderic44** [ev3dev/vscode-ev3dev-browser#71]
Hello.
When I write a script under VS Code for EV3, in the PROBLEMS tab, VSCode displays me full !  :(
Example. If I write a simple script like :

from ev3dev.ev3 import *
m = LargeMotor ('outA')

I have 2 problems:

[pylint] Unable to import 'ev3dev.ev3' [E0401]
[pylint] Undefined variable 'LargeMotor' [E0602]

However, my scripts run and work. But did I do a bad installation of VS Code?

**Comment by WasabiFan** [comment]
Vscode is fine. The reason it displays errors is that it can't find the ev3dev module _on your computer_ — when you actually run your code on the brick the module is installed there. If you'd like to install it on your computer too you can run the command `pip install python-ev3dev` (or `python-ev3dev2` if you're using version 2 on Stretch).

**Comment by marchanderic44** [comment]
I feel like I fall into all the basic traps like a student ... :)
Indeed, by installing this library, I no longer have an error message. Thank you.
NB: to install on my PC, I rather used the command:
python.exe -m pip install python-ev3dev

However, in the PROBLEMS tab, I now have 64 warnings (still for my program with the 2 lines of code):
[pylint] Imported import list_motors from wildcard [W0614]
[pylint] Unused import OUTPUT_A from wildcard import [W0614]
[pylint] Unused import OUTPUT_B from wildcard import [W0614]
...
The goal was to identify programmatic errors more quickly, but as there is a lot of warning that appears, I do not think it is interesting to install this library on the PC.

**Comment by dlech** [comment]
Instructions on how to make the errors go away has been added here: https://github.com/ev3dev/vscode-hello-python#code-completion
