### ISSUE TITLE
/usr/bin/env: 'python3 \r': No such file or directory

### ISSUE THREAD

**Issue by dihangit** [ev3dev/vscode-ev3dev-browser#72]
When I run the program on ev3, I am getting the following error code on output
```
Starting: brickrun --directory="/home/robot/ev3test" "/home/robot/ev3test/speak.py"
Started.
----------
/usr/bin/env: 'python3 \r': No such file or directory
----------
Exited with error code 127.
```

**Comment by WasabiFan** [comment]
At the bottom of the window, click where it says "CRLF" and then choose "LF". Then try running the program again.

**Comment by dihangit** [comment]
I changed to LF, no luck getting the same error. Also noticed with stretched image on EV3, there is no 
/usr/bin/env directory, there is an env file. Output below:

Starting: brickrun --directory="/home/robot/ev3test" "/home/robot/ev3test/speak.py"
Started.
----------
/usr/bin/env: 'python3 \r': No such file or directory
----------
Exited with error code 127.

**Comment by dlech** [comment]
Did you download the file to the EV3 again after making the change?

Is there a trailing space after `#!/usr/bin/env python3` that is causing a problem?

**Comment by bpmerkel** [comment]
Recommend closing this issue
