### ISSUE TITLE
Cannot open the SSH Terminal

### ISSUE THREAD

**Issue by 98moonlight** [ev3dev/vscode-ev3dev-browser#73]
Hello,

I can't open the SSH on the EV3. Under EV3DEV Device Browser, after pressing the Open SSH Terminal, the terminal screen remains blank. I can't input anything into the terminal as well.

Here is the screenshot, with the extensions.json:
![ss_1](https://user-images.githubusercontent.com/19956058/52159335-9327d580-26dd-11e9-978f-f7bc3f00203c.jpg)

Do let me know if I will able to retrieve any form of error log for this issue.

Thank you!

**Comment by dlech** [comment]
Thanks for reporting. Fixed in v1.0.1
