### ISSUE TITLE
show warning when no files are selected by filters for download

### ISSUE THREAD

**Issue by dlech** [ev3dev/vscode-ev3dev-browser#75]
This would help diagnose problems like https://github.com/ev3dev/vscode-ev3dev-lang-python/issues/1

If the `include` and `exclude` settings filter out all files in a project, then we should show a warning that says that nothing was selected for download. The current behavior is to show a download progress bar for a moment and then an info box stating that download was successful.

**Comment by ndward** [comment]
I've just tried the latest (18 Feb 2019) image and noticed that pressing F5 no longer causes any scripts to be downloaded to the brick! Therefore each time I change my script I have to click the 'Send workspace to device' icon before I can run the script (by pressing F5). Is this related to the theme of this issue? Should I make a separate issue? Can you confirm this? Is this a deliberate change? It seems hugely annoying to me, though I would be in favor of not having to download the entire project folder to the brick each time I modify just one file. Maybe the best would be to have F5 download the entire folder as before and a different key such as F6 could download and run just the active script?
BTW, the link in the above message doesn't seem to work?

**Comment by WasabiFan** [comment]
@ndward that sounds like it should be a new issue.
