### ISSUE TITLE
ev3dev-browser

### ISSUE THREAD

**Issue by johnsmith2014w** [ev3dev/vscode-ev3dev-browser#77]
The new ev3dev-browser did not work. No Brick detected. Once the old one worked. Thanks.

**Comment by dlech** [comment]
Can you please give the exact steps to reproduce the problem? What operating system? What versions of everything?

**Comment by johnsmith2014w** [comment]
Thanks. Once it worked very well. However, I connected through USB, no brick detected.
The operating system is Win8.  The Vs code is x64 1.31.1, the lego is Model: 31313, brickman v0.10.0, Kernel :4.14.61-ev3dev-2.2.2-ev3, ev3dev-browser is 1..01. I used USB connection.

**Comment by dlech** [comment]
If you install v1.0.0, does it work?

![image](https://user-images.githubusercontent.com/963645/53750906-a363d980-3e70-11e9-82b0-80d85c686788.png)

![image](https://user-images.githubusercontent.com/963645/53750955-c8584c80-3e70-11e9-8ed0-45c910846fa1.png)

**Comment by johnsmith2014w** [comment]
Thank you very much. I deleted the vscode completely and reinstall all the extensions, it works now.

**Comment by dlech** [comment]
So v1.0.1 is working for you now? Can we close the issue?

**Comment by johnsmith2014w** [comment]
Yes, Thank you very much.
