### ISSUE TITLE
SSH terminal is not working on Windows 10

### ISSUE THREAD

**Issue by dlech** [ev3dev/vscode-ev3dev-browser#78]
Using Windows 10 1809 and VS Code 1.31.1.

When you try to open an SSH terminal, it is blank:

![image](https://user-images.githubusercontent.com/963645/53768935-eee1ac00-3e9f-11e9-8e7d-3ca4bf4d6e1c.png)

Scrolling up reveals there is something actually there, but no prompt.

![image](https://user-images.githubusercontent.com/963645/53768966-0ae54d80-3ea0-11e9-8639-c505619158e3.png)

WORKAROUND: Pressing <kbd>Enter</kbd> at least 6 times will finally show the prompt.

![image](https://user-images.githubusercontent.com/963645/53769000-29e3df80-3ea0-11e9-8819-1e734f5d2c1f.png)

This is a know bug in VS Code/Windows: https://github.com/Microsoft/vscode/issues/57803

According to that issue, it should get fixed in the next Windows release (builds 18309 and later).

**Comment by dlech** [comment]
Confirmed fixed on Windows 10 build 18342

![image](https://user-images.githubusercontent.com/963645/53775584-c2865980-3eb8-11e9-841c-19b3f205ac9d.png)

**Comment by bpmerkel** [comment]
Recommend closing this issue, as fixed with VS Code release

**Comment by dlech** [comment]
According to https://reports.adduplex.com/#/r/2020-01, 2/3 Windows 10 users are on 1903 or newer, so probably safe to close now.
