### ISSUE TITLE
Failed to connect to ev3dev: connect EACCES 

### ISSUE THREAD

**Issue by Cutters** [ev3dev/vscode-ev3dev-browser#81]
Hi there,

I'm a few years removed from programming and I recently got myself an Ev3. I'm trying to set it up to run EV3Dev and EV3 Python via VS Code and have followed all of the instructions at ev3dev.org as well as ev3python.com. I'm running the most current versions of all software from those sites.

Everything has gone to plan and I can communicate with the brick via PuTTy, so I'm somewhat confident in my setup. I've moved on to VS Code and the EV3dev-browser extension, and that's where I've hit a snag. The extension launched fine, and I can see my device when I click "click here to connect to a device," but when I click on it, I immediately get an error in the bottom left corner that reads "Failed to connect to ev3dev: connect EACCES." This error has persisted for two days of troubleshooting, reinstalling, swapping out SD cards and re-imaging, connecting via bluetooth and USB...

Edit: OS is Win10, VS Code is x64 1.32.3, Brickman is v0.10.0, Kernel 4.14.80-ev3dev-2.3.1-ev3

Here's what my screen looks like:

![Capture](https://user-images.githubusercontent.com/49172947/55365346-94496900-54ba-11e9-9a6b-1667e837b9fe.PNG)

Help!

**Comment by dlech** [comment]
Windows? Which version? Firewall problem?

**Comment by Cutters** [comment]
Just edited with more info:

OS is Win10, VS Code is x64 1.32.3, Brickman is v0.10.0, Kernel 4.14.80-ev3dev-2.3.1-ev3

**Comment by Cutters** [comment]
Ref: Firewall problem - I'm running ESET Internet Security. I tried both disabling it and flipping it into interactive mode and allowing the traffic through VS Code, no luck.

**Comment by Cutters** [comment]
More info: I'm using a DHCP connection on the brick. It normally loads with an IP address in the 169.254.xxx.xx range, and in this case it can connect with SSP (PuTTy). If I share my wireless internet connection with the brick via windows network connections, I get 192.168.xxx.xxx and I can no longer connect to SSH (access denied). In both cases, I cannot connect to VS Code via the EV3dev-browser.

**Comment by dlech** [comment]
The extensions in VS Code run in a separate process from the main VS Code, so perhaps the security software could still be blocking it?

Also, with USB, if you don't need an Internet connection, it will work better if you don't enable USB on the EV3. In other words, if you are using only USB and you seen an IP address, then the USB gadget device is on and needs to be turned off. USB is supposed to work with VS Code when there is no IP address displayed on the EV3.

**Comment by Cutters** [comment]
SOLVED!

I had been using NordVPN while I was in Europe a few months ago and, although I had uninstalled it, the network connections remained and were causing the issue. I deleted them and now we're seeing a green light!

Thanks!
