### ISSUE TITLE
Failed to connect to ev3: Timed out while waiting for handshake via USB on Windows 8

### ISSUE THREAD

**Issue by johnsmith2014w** [ev3dev/vscode-ev3dev-browser#82]
Hi, the problem is :Failed to connect to ev3: Timed out while waiting for handshake. Thank you very much.

**Comment by dlech** [comment]
How are you connecting? USB, Bluetooth, Wi-Fi?

**Comment by johnsmith2014w** [comment]
Thanks. usb, no device detected.

**Comment by dlech** [comment]
What operating system?

**Comment by johnsmith2014w** [comment]
Windows 8.

David Lechner <notifications@github.com>于2019年4月2日 周二14:21写道：

**Comment by dlech** [comment]
Which ev3dev SD card image are you using?

**Comment by johnsmith2014w** [comment]
The latest ev3dev stretch.

David Lechner <notifications@github.com>于2019年4月2日 周二14:36写道：

**Comment by bean07** [comment]
@dlech I have the same issue, please help.

**Comment by johnsmith2014w** [comment]
@dlech Where can I find the IP address of the ev3? Thanks. Because I can not find the ev3  device, therefore I need to input the IP address of the ev3.

**Comment by Tooshe** [comment]
Same on win10?
It was working but it stopped working after installing libusb for this https://github.com/walac/pyusb
It'd be nice to have it connecting again?

**Comment by dlech** [comment]
Can you please post screenshots of the error?

**Comment by Tooshe** [comment]
![error](https://user-images.githubusercontent.com/49989556/56749084-64913680-67c4-11e9-923b-ba186ec90f56.jpg)

**Comment by Tooshe** [comment]
![error](https://user-images.githubusercontent.com/49989556/56749441-16c8fe00-67c5-11e9-9fa3-e9ed2fffe962.jpg)

**Comment by dlech** [comment]
Can you please try manually installing the `.vsix` file from https://github.com/ev3dev/vscode-ev3dev-browser/releases/tag/v1.0.4-beta1 to see if it fixes the problem?

**Comment by Tooshe** [comment]
It's working again, thank you. :)

**Comment by dlech** [comment]
This should be fixed in v1.0.4.

**Comment by johnsmith2014w** [comment]
Thank you very much. That's so great.

**Comment by patricksterlin** [comment]
Hi,
I'm having the same problem.
ev3dev-browser v1.2.1

I would be really grateful for some help...

**Comment by dlech** [comment]
This issue has been closed for many years. It would be best to start a new issued with very detailed information on how to reproduce the problem.
