### ISSUE TITLE
Debian version: fail to pop up window when click "Click here to connect to a device"

### ISSUE THREAD

**Issue by mingli-ts** [ev3dev/vscode-ev3dev-browser#83]
**Describe the bug**
The latest Debian version of this browser can not show pop up window when click "Click here to connect to a device" below "EV3DEV DEVICE BROWSER". 

**To Reproduce**
1. Install latest version of vscode and this browser on Debian
2. Click on 'Click here to connect to a device'

**Desktop (please complete the following information):**
 - OS and version: Debian, latest version

**Comment by dlech** [comment]
So you are using Debian sid?

**Comment by dlech** [comment]
You need to have the `avahi-daemon` package installed and running.

**Comment by mingli-ts** [comment]
I'll give it a try tonight. Meanwhile can you please add this to the installation instructions? A lot of school kids are using Chromebook to run vscode. They might be trouble by this. Thanks

**Comment by J370** [comment]
I had the same issue as mentioned and @dlech recommendation works.

**Comment by dlech** [comment]
Should be fixed in v1.0.4. The extension will now fall back to a (buggy) native javascript implementation of mDNS. Installing avahi is still preferred since it will give better results.
