### ISSUE TITLE
multiple ev3dev devices

### ISSUE THREAD

**Issue by JorgePe** [ev3dev/vscode-ev3dev-browser#84]
Hi.
I am trying to deploy same code to several (well, 2: 'iota' and 'alpha') EV3. Although the code is the same the behavior will not be as I am using the hostname to separate roles in an IoT mesh.

Both have Wi-Fi and Avahi is working.

Device browser always shows just one. I need to disconnect and only then I have the option to connect to another, then both show up. But after connecting to the other I only have this one on the ev3dev Device Browser panel.
I was expecting to have both - one connected, the other disconnected, so every time I would need to upload the script it would be just a matter of disconnect/connect the proper one (although an option to broadcast the same file to all would be nice).

I saw issue #2 so is this a by design option?

**Comment by dlech** [comment]
Yes, this is by design. It looks like there is a command to open the same workspace in a new window that would allow you to connect to a second device. https://github.com/Microsoft/vscode/issues/2686#issuecomment-441350180

**Comment by JorgePe** [comment]
Thanks. It works.
With 2 bricks it's acceptable, with more bricks (if/when I have them) I think I'll make some bash script to broadcast the files through rsync (or invoke git, probably better).

For others:
Manage > Command Palette... > Worskspaces: Duplicate Workspace in New Window
