### ISSUE TITLE
Device not listed in Linux

### ISSUE THREAD

**Issue by bidaian** [ev3dev/vscode-ev3dev-browser#86]
The ev3 device does not show up in the list of devices (Debian buster)

**To Reproduce**
1. start Visual Studio Code
2. connect the device via USB
3 go to EV3DV Device Browser

**Additional context**
I can manually add the device as ev3dev.local, with the address I get by doing:

`$ ping ev3dev.local` or

`$avahi-browse -a --resolve`

If I do:

`$avahi-browse -a`

it also shows up. Any idea on why it doesn't show up automatically?

`+   usb0 IPv4 ev3dev                                        SSH Remote Terminal  local`
`+   usb0 IPv4 ev3dev                                        SFTP File Transfer   local`

**Comment by dlech** [comment]
This extension only uses IPv6, so there should be IPv6 entries in `avahi-browse` as well. If you don't see those, that is why it is not working. Perhaps IPv6 is disabled on your computer?

**Comment by bidaian** [comment]
IPv6 was disabled in avahi-daemon. Added:

`use-ipv6=yes`

restarted the daemon, and now it works! Thanks for pointing out the need for IPv6.
