### ISSUE TITLE
automate using `brickrun -r`

### ISSUE THREAD

**Issue by dlech** [ev3dev/vscode-ev3dev-browser#90]
VS Code now has an actual terminal API, so we can actually automate using `brickrun -r` now.

_Originally posted by @dlech in https://github.com/ev3dev/vscode-ev3dev-browser/issues/67#issuecomment-570717757_

This will redirect stdout and stdin to VS Code. This could be nice for beginning users who don't know about stderr and for programs that need simple remote input via a terminal window.

**Comment by scprotz** [comment]
I tested using "brickrun -r" (modified extension.js) in the extensions folder for visual studio code and it works as expected.  I can now receive stdout and stderr messages in the VSCode console.

This should definitely be a changeable setting the VSCode extension setting for ev3dev-browser.

**Comment by dlech** [comment]
Fixed in `v1.1.0-beta.1` 

https://github.com/ev3dev/vscode-ev3dev-browser/releases
