### ISSUE TITLE
edit and remove devices

### ISSUE THREAD

**Issue by MenschMarcus** [ev3dev/vscode-ev3dev-browser#91]
I want to administer my ev3dev devices. The ev3dev device browser lets me
- add a new device
- connect to a device
- connect to a different device

but it is lacking the - to me - important features:
- edit a device (e. g. change name or IP address)
- remove a device

I made a mistake when connecting to the ev3 device the first time so I had to add another device. And now it is frustrating that there are two devices, the first is the wrong one and I can not get rid of it.

**Comment by dlech** [comment]
This can be done by editing the user settings in VS Code.

**Comment by MenschMarcus** [comment]
Alright, cool! For anybody who wants to know how this works:
<Ctrl> + <P> -> "Preferences: Open User Settings"
Extensions > ev3dev browser configuration
Edit in settings.json
-> Edit and delete devices

Thank you so much!

**Comment by dlech** [comment]
Great! Thanks for the follow up with steps on how to do it. :smile:
