### ISSUE TITLE
Failed to connect to ev3: Timed out while waiting for handshake via USB on Windows 10

### ISSUE THREAD

**Issue by khomthomas** [ev3dev/vscode-ev3dev-browser#96]
![Capture](https://user-images.githubusercontent.com/60713717/73884486-95120080-482b-11ea-821d-2220fabc4743.PNG)

**Comment by dlech** [comment]
Can you give the exact steps to reproduce the problem?

**Comment by jirklspot** [comment]
I have the same issue. brick is appeared in VS Code Command Pallette for the first time. After than Keep getting the same error "ev3dev" on the "EV3DEV DEVICE BROWSER" windows keep showing as RED and it throws the error "Failed to connect to ev3dev: Timeout while waiting for handshake" 

Platform : Windows 10


Brick shows ip address on the top, **State: Connected** and IP Address keeps changing whenever i do "Reconnect"

**Comment by dlech** [comment]
In v1.1.0, the timeout is increased from 20 to 30 seconds. It is also now configurable via a setting if that is not long enough.
