### ISSUE TITLE
Bluetooth paired EV3 brick is not listed in VS Code Command Pallet (Windows 10)

### ISSUE THREAD

**Issue by jirklspot** [ev3dev/vscode-ev3dev-browser#97]
**Describe the bug**
Hi
Bluetooth paired EV3 brick is not listed in VS Code Command Pallette 

**To Reproduce**
1. Open VS Code
2. Install Python and Configured Python Interpreter (Python 3.7.6.64 bit) 
2. Install **LEGO® MINDSTORMS® EV3 MicroPython** extension which comes with **ev3dev-browser** 
3, Power on my EV3 brick, Name it and  Enable Bluetooth
4. From Windows 10 PC, Enabled Bluetooth connection settings and able to **Pair** the brick.
5. Open  Command Palette
6. Click  ">ev3dev: Connect to a device"
7. I don't see my brick listed at the command palette (no ip-address part of "Brick"s properties too to try by ip-address

**Environment**
- Windows 10 Pro
- VS Code : 1.42.1
- Python 3.7.6
- LEGO® MINDSTORMS® EV3 MicroPython - v1.0.3, ev3dev-browser 1.0.4

**Expected behavior**
My EV3 brick should be listed to make a connection

**Desktop (please complete the following information):**
- Windows 10 Pro

**Additional context**
Able to pair ev3 brick through Bluetooth and its successful but its not listed in VS Code.

**Comment by dlech** [comment]
Thanks for the detailed information. It is very helpful.

It looks like you are missing the step to make a network connection via Bluetooth. See step 6 at https://www.ev3dev.org/docs/tutorials/connecting-to-the-internet-via-bluetooth/.

On Windows 10, Internet Connection Sharing doesn't work with Bluetooth for some reason (this is a problem with Windows Bluetooth in general, not just with ev3dev). But after 10 seconds or so, the EV3 will still be given a network address that can be seen at the top of the screen. After this address is visible, the EV3 should appear in the list of devices in VS Code.

**Comment by jirklspot** [comment]
> Thanks for the detailed information. It is very helpful.
> 
> It looks like you are missing the step to make a network connection via Bluetooth after pairing. See step 6 at https://www.ev3dev.org/docs/tutorials/connecting-to-the-internet-via-bluetooth/.
> 
> On Windows 10, Internet Connection Sharing doesn't work with Bluetooth for some reason (this is a problem with Windows Bluetooth in general, not just with ev3dev). But after 10 seconds or so, the EV3 will still be given a network address that can be seen at the top of the screen. After this address is visible, the EV3 should appear in the list of devices in VS Code.

Thanks for your respnose. I don't see Step 6 during my Bluetooth setup. I do see Bluetooth  (under tools option) and under that Visibility, BlueTooth and iPhone/iPad/iPod checkboxes where I checked on Visibility and BlueTooth. 

As you said, I dont see any network address and thus EV3 is not appearing in VS Code

Can you please help me?

**Comment by dlech** [comment]
If you are seeing iPhone/iPad/iPod checkboxes, then you are not using ev3dev. The VS Code extension is not compatible with the standard LEGO firmware and requires that ev3dev (a different operating system) is installed on a microSD card and run on the EV3. More info is at https://www.e3dev.org.

**Comment by jirklspot** [comment]
Aha!!! Great That's the issue. I followed all the steps and setup ev3dev in my brick. Things worked now. But "connection" is not seamless. As it's resolved my original issue, I'm closing this ticket...

Thanks a bunch!!!
